---
- name: Install Jenkins on Ubuntu 20.04
  hosts: jenkins
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_become_pass: erkut+2023

  tasks:
    - name: Ensure system packages are up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: update
      apt:
        name: '*'
        state: latest
    

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins GPG key
      ansible.builtin.shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo gpg --dearmor -o /usr/share/keyrings/jenkins-archive-keyring.gpg
      args:
        warn: no

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-archive-keyring.gpg] http://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins service is running and enabled
      systemd:
        name: jenkins
        state: started
        enabled: yes
