---
- name: Set up Jenkins in a Docker container
  hosts: jenkins
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Jenkins Docker image
      ansible.builtin.docker_image:
        name: jenkins/jenkins:lts
        source: pull

    - name: Create Jenkins data volume
      ansible.builtin.docker_volume:
        name: jenkins-data

    - name: Create Jenkins Docker client certificates volume
      ansible.builtin.docker_volume:
        name: jenkins-docker-certs

    - name: Run Jenkins container
      ansible.builtin.docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - "jenkins-data:/var/jenkins_home"
          - "jenkins-docker-certs:/certs/client"
        env:
          DOCKER_TLS_VERIFY: "1"
          DOCKER_CERT_PATH: "/certs/client"
          DOCKER_HOST: "tcp://192.168.220.3:2376"
