---
- name: Setup Kubernetes
  hosts: k8s
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_become_pass: erkut+2023
  tasks:
    - name: Copy join command from Ansiblehost to the worker nodes.
      become: yes
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 777
    - name: Join the Worker nodes to the cluster.
      become: yes
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not
